version: "3.8"

services:
  client:
    build:
      context: ./client
    image: client
    ports:
      - "4200:4200"
    container_name: client


  api:
    build:
      context: ./nodeapi
    image: nodeapi
    ports:
      - "5000:5000"
    restart: always
    container_name: api

  webapi:
    build:
      context: ./javaapi
    image: webapi
    ports:
      - "9000:9000"
    restart: always
    container_name: webapi

  nginx:
    build:
      context: ./nginx  # Path to the directory where your Dockerfile is located
    image: nginx  # Custom image name
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  emongo:
    image: mongo:4
    container_name: emongo
    environment:
      - MONGO_INITDB_DATABASE=epoc
    ports:
      - "27017:27017"

  emartdb:
    image: mysql:8.0.33
    container_name: emartdb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=emartdbpass
      - MYSQL_DATABASE=books
