apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: nodeapi
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_INITDB_DATABASE
              value: "epoc"
            - name: MONGO_URL            # Adding the MongoDB connection string
              value: "mongodb://mongo-service:27017/epoc"


