apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 4200       # Dış dünyaya açılan port
      targetPort: 4200 # Pod içinde Angular'ın dinlediği port
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: client  # Docker Compose'ta oluşturduğunuz yerel image
          imagePullPolicy: Never   # Yerel image kullanımı için gerekli ayar
          ports:
            - containerPort: 4200   # Angular uygulamanızın portu
